/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author LUIS
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        mnuAutor = new javax.swing.JMenu();
        mnuiInsert = new javax.swing.JMenuItem();
        mnuiAct = new javax.swing.JMenuItem();
        mnuiMostrar = new javax.swing.JMenuItem();
        mnuiEliminar = new javax.swing.JMenuItem();
        mnuLibro = new javax.swing.JMenu();
        mnuiInsertL = new javax.swing.JMenuItem();
        mnuiActL = new javax.swing.JMenuItem();
        mnuiMostrarL = new javax.swing.JMenuItem();
        mnuiEliminarL = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Biblioteca");

        mnuAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/autor.png"))); // NOI18N
        mnuAutor.setText("Autor");

        mnuiInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/in.png"))); // NOI18N
        mnuiInsert.setText("Insertar");
        mnuAutor.add(mnuiInsert);

        mnuiAct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/recargar.png"))); // NOI18N
        mnuiAct.setText("Actualizar");
        mnuAutor.add(mnuiAct);

        mnuiMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/base.png"))); // NOI18N
        mnuiMostrar.setText("Autores Registrados");
        mnuAutor.add(mnuiMostrar);

        mnuiEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Delete.png"))); // NOI18N
        mnuiEliminar.setText("Eliminar");
        mnuiEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiEliminarActionPerformed(evt);
            }
        });
        mnuAutor.add(mnuiEliminar);

        jMenuBar2.add(mnuAutor);

        mnuLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/libro.png"))); // NOI18N
        mnuLibro.setText("Libros");

        mnuiInsertL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/in.png"))); // NOI18N
        mnuiInsertL.setText("Insertar");
        mnuiInsertL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiInsertLActionPerformed(evt);
            }
        });
        mnuLibro.add(mnuiInsertL);

        mnuiActL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/recargar.png"))); // NOI18N
        mnuiActL.setText("Actualizar");
        mnuLibro.add(mnuiActL);

        mnuiMostrarL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/base.png"))); // NOI18N
        mnuiMostrarL.setText("Mostrar Registros");
        mnuLibro.add(mnuiMostrarL);

        mnuiEliminarL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Delete.png"))); // NOI18N
        mnuiEliminarL.setText("Eliminar");
        mnuLibro.add(mnuiEliminarL);

        jMenuBar2.add(mnuLibro);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuiEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuiEliminarActionPerformed

    private void mnuiInsertLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiInsertLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuiInsertLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuBar jMenuBar2;
    public javax.swing.JMenu mnuAutor;
    public javax.swing.JMenu mnuLibro;
    public javax.swing.JMenuItem mnuiAct;
    public javax.swing.JMenuItem mnuiActL;
    public javax.swing.JMenuItem mnuiEliminar;
    public javax.swing.JMenuItem mnuiEliminarL;
    public javax.swing.JMenuItem mnuiInsert;
    public javax.swing.JMenuItem mnuiInsertL;
    public javax.swing.JMenuItem mnuiMostrar;
    public javax.swing.JMenuItem mnuiMostrarL;
    // End of variables declaration//GEN-END:variables
}
